# Generated by Django 4.2.7 on 2023-11-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='brand name', max_length=20)),
                ('image', models.ImageField(blank=True, default='static/home/brand/br1.png/', null=True, upload_to='images/brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(blank=True, default='static/home/images/clients/c1.png', null=True, upload_to='images/clients/')),
                ('message', models.TextField(default='This is client message')),
                ('client_full_name', models.TextField(max_length=140)),
                ('country', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Feature_cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='static/home/images/new-cars-model/ncm1.png', null=True, upload_to='images/featured-cars/')),
                ('year', models.PositiveSmallIntegerField(default=2017)),
                ('model', models.CharField(default='3100 Mi', max_length=45)),
                ('horse_power', models.PositiveSmallIntegerField(default=240)),
                ('car_type', models.CharField(choices=[('mexanik', 'Mexanik'), ('automatic', 'Automatic')], max_length=14)),
                ('car_name', models.CharField(default='BMW 6-Series Gran Coupe', max_length=140)),
                ('price', models.CharField(default='$500,500', max_length=20)),
                ('about', models.TextField(default='This is car about for sale')),
            ],
        ),
        migrations.CreateModel(
            name='New_cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, default='static/home/images/new-cars-model/ncm1.png', null=True, upload_to='images/new-cars/')),
                ('car_name', models.CharField(default='BMX | M5', max_length=140)),
                ('car_about', models.TextField(default='This is car about')),
            ],
            options={
                'db_table': 'New_car',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='This is title', max_length=110, verbose_name='title')),
                ('about', models.TextField(default='This is about', verbose_name='About')),
            ],
            options={
                'db_table': 'Servis',
            },
        ),
    ]
